### PR TITLE
docs: Updated readme

### PR DESCRIPTION
**Pull request by vinzvinci**
# Description

I updated our readme to make it better. 

#### Improvements:
- Added more detailed information about this project
- They will know what is the topic in this repository
- Added design to make the readme stand out
 
**Readme demo is here:** https://github.com/vinzvinci/community#community-discussion

# Code of Conduct

By submitting this PR, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/community/blob/main/CODE_OF_CONDUCT.md) 🖖

### CODE REVIEW

**Comment by coinhu** [comment]
cheers

**Comment by aggre** [comment]
@vinzvinci Good changes! Thank you for the PR! But the Dev Challenge is closed, so the application is disabled now, is that still no problem?

**Comment by vinzvinci** [comment]
No problem with that @aggre, didn't know there's a dev challenge ^^, I'm curious about why's the wallet there, maybe we can merge this for the README only? Yeah?

**Comment by vinzvinci** [comment]
I removed the dev challenge, it may confuse everyone. We should update our featured topic when it's done, I put the Dev Dapp Starter Grants

**Comment by vinzvinci** [comment]
Time to merge🎉

**Comment by aggre** [comment]
@vinzvinci thanks!!

**Pull request merged**
